name: CI
on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build-linux:
    name: Linux-autoTests
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install cmake qt6-base-dev qt6-base-dev-tools qt6-svg-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools zlib1g-dev pkg-config libhunspell-dev libquazip1-qt6-dev

    - name: Configure
      run: cmake -DTEXSTUDIO_ENABLE_TESTS=ON -DTEXSTUDIO_BUILD_ADWAITA=OFF -DCMAKE_BUILD_TYPE=Debug .

    - name: Build
      run: make -j 4

    - name: Test
      run: QT_QPA_PLATFORM=offscreen ./texstudio --auto-tests
